// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/energiqualif/HomeActuel.tsx": () => import("../components/mockups/energiqualif/HomeActuel.tsx"),
  "./components/mockups/energiqualif/HomeAmeliore.tsx": () => import("../components/mockups/energiqualif/HomeAmeliore.tsx"),
  "./components/mockups/energiqualif/ProjetListe.tsx": () => import("../components/mockups/energiqualif/ProjetListe.tsx")
};
